### ISSUE TITLE
What is the difference between ImageNet c acc and ImageNet mCE? 100 -ImageNetc acc = mCE isn't it?

### ISSUE THREAD

**Issue by seominseok0429** [bethgelab/game-of-noise#2]
What is the difference between ImageNet c acc and ImageNet mCE? 100 -ImageNetc acc = mCE isn't it?

**Comment by EvgeniaAR** [comment]
Hi there,

no,  100 -ImageNetc acc = mCE is not correct. For mCE, one normalizes all corruptions by the corruption error of AlexNet (see Eq. on the top of page 5 [here](https://arxiv.org/pdf/1903.12261.pdf)).

**Comment by seominseok0429** [comment]
Thanks so much for the kind explanation. And your research has inspired me a lot. Thank you so much for your great research!

**Comment by EvgeniaAR** [comment]
Thank you for your kind words! :)
